[alembic]
# path to migration scripts
script_location = migrations

# SQLAlchemy database URL. This will be overridden by `env.py`
# but Alembic requires a valid ini file with this key present.
sqlalchemy.url = dummy_value_for_sqlalchemy_url

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S