"""add name and description columns to the step

Revision ID: b273a6af9212
Revises: f7186500bf92
Create Date: 2026-06-14 21:29:42.322811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b273a6af9212'
down_revision: Union[str, None] = 'f7186500bf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('name', sa.String(length=255), nullable=False, server_default="Unnamed Step"))
    op.add_column('steps', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'description')
    op.drop_column('steps', 'name')
    # ### end Alembic commands ###
