"""create recipe and step tables

Revision ID: f7186500bf92
Revises: 
Create Date: 2026-06-14 10:20:20.366049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7186500bf92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.Enum('take_image', 'unscrewing', name='step_type_enum'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'order_index', name='uq_step_recipe_order')
    )
    op.create_table('take_image_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('include_pointcloud', sa.Boolean(), nullable=False),
    sa.Column('image_scope', sa.Enum('full_battery', 'section', name='image_scope_enum'), nullable=False),
    sa.Column('center_x', sa.Integer(), nullable=True),
    sa.Column('center_y', sa.Integer(), nullable=True),
    sa.CheckConstraint("(image_scope = 'section' AND center_x IS NOT NULL AND center_y IS NOT NULL) OR (image_scope = 'full_battery' AND center_x IS NULL AND center_y IS NULL)", name='ck_take_image_coords_match_scope'),
    sa.CheckConstraint('center_x IS NULL OR center_x >= 0', name='ck_take_image_center_x_nonneg'),
    sa.CheckConstraint('center_y IS NULL OR center_y >= 0', name='ck_take_image_center_y_nonneg'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('unscrewing_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('unscrewing_mode', sa.Enum('automatic', 'specific', name='unscrewing_mode_enum'), nullable=False),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.CheckConstraint("(unscrewing_mode = 'specific' AND coordinate_x IS NOT NULL AND coordinate_y IS NOT NULL) OR (unscrewing_mode = 'automatic' AND coordinate_x IS NULL AND coordinate_y IS NULL)", name='ck_unscrew_coords_match_mode'),
    sa.CheckConstraint('coordinate_x IS NULL OR coordinate_x >= 0', name='ck_unscrew_x_nonneg'),
    sa.CheckConstraint('coordinate_y IS NULL OR coordinate_y >= 0', name='ck_unscrew_y_nonneg'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unscrewing_steps')
    op.drop_table('take_image_steps')
    op.drop_table('steps')
    op.drop_table('recipes')
    # ### end Alembic commands ###
